version: '3.9'

services:
  sqlserver:
    build: ./sqlserver
    container_name: sql-container
    ports:
      - "1433:1433"

  api:
    build: ./ReplacementTool.API
    container_name: api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ReplacementToolDb;User Id=sa;Password=4DM1NP4$$W0RD9173;TrustServerCertificate=True;

  angular:
    build: ./FRONT
    container_name: angular
    ports:
      - "4200:80"
    depends_on:
      - api
